// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commands.proto

#ifndef PROTOBUF_commands_2eproto__INCLUDED
#define PROTOBUF_commands_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace pas {
class ArtistCountQuery;
class ArtistCountQueryDefaultTypeInternal;
extern ArtistCountQueryDefaultTypeInternal _ArtistCountQuery_default_instance_;
class ClearDeviceCommand;
class ClearDeviceCommandDefaultTypeInternal;
extern ClearDeviceCommandDefaultTypeInternal _ClearDeviceCommand_default_instance_;
class DacInfo;
class DacInfoDefaultTypeInternal;
extern DacInfoDefaultTypeInternal _DacInfo_default_instance_;
class FolderCountQuery;
class FolderCountQueryDefaultTypeInternal;
extern FolderCountQueryDefaultTypeInternal _FolderCountQuery_default_instance_;
class GenericPB;
class GenericPBDefaultTypeInternal;
extern GenericPBDefaultTypeInternal _GenericPB_default_instance_;
class OneFloat;
class OneFloatDefaultTypeInternal;
extern OneFloatDefaultTypeInternal _OneFloat_default_instance_;
class OneInteger;
class OneIntegerDefaultTypeInternal;
extern OneIntegerDefaultTypeInternal _OneInteger_default_instance_;
class OneString;
class OneStringDefaultTypeInternal;
extern OneStringDefaultTypeInternal _OneString_default_instance_;
class PauseDeviceCommand;
class PauseDeviceCommandDefaultTypeInternal;
extern PauseDeviceCommandDefaultTypeInternal _PauseDeviceCommand_default_instance_;
class PlayTrackCommand;
class PlayTrackCommandDefaultTypeInternal;
extern PlayTrackCommandDefaultTypeInternal _PlayTrackCommand_default_instance_;
class ResumeDeviceCommand;
class ResumeDeviceCommandDefaultTypeInternal;
extern ResumeDeviceCommandDefaultTypeInternal _ResumeDeviceCommand_default_instance_;
class Row;
class RowDefaultTypeInternal;
extern RowDefaultTypeInternal _Row_default_instance_;
class SelectQuery;
class SelectQueryDefaultTypeInternal;
extern SelectQueryDefaultTypeInternal _SelectQuery_default_instance_;
class SelectResult;
class SelectResultDefaultTypeInternal;
extern SelectResultDefaultTypeInternal _SelectResult_default_instance_;
class StopDeviceCommand;
class StopDeviceCommandDefaultTypeInternal;
extern StopDeviceCommandDefaultTypeInternal _StopDeviceCommand_default_instance_;
class TrackCountQuery;
class TrackCountQueryDefaultTypeInternal;
extern TrackCountQueryDefaultTypeInternal _TrackCountQuery_default_instance_;
class TwoIntegers;
class TwoIntegersDefaultTypeInternal;
extern TwoIntegersDefaultTypeInternal _TwoIntegers_default_instance_;
class WhatDeviceCommand;
class WhatDeviceCommandDefaultTypeInternal;
extern WhatDeviceCommandDefaultTypeInternal _WhatDeviceCommand_default_instance_;
class WhenDeviceCommand;
class WhenDeviceCommandDefaultTypeInternal;
extern WhenDeviceCommandDefaultTypeInternal _WhenDeviceCommand_default_instance_;
class WhoDeviceCommand;
class WhoDeviceCommandDefaultTypeInternal;
extern WhoDeviceCommandDefaultTypeInternal _WhoDeviceCommand_default_instance_;
}  // namespace pas

namespace pas {

namespace protobuf_commands_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_commands_2eproto

enum LogLevel {
  FATAL = 0,
  MINIMAL = 1,
  CONVERSATIONAL = 2,
  VERBOSE = 3,
  LogLevel_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  LogLevel_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool LogLevel_IsValid(int value);
const LogLevel LogLevel_MIN = FATAL;
const LogLevel LogLevel_MAX = VERBOSE;
const int LogLevel_ARRAYSIZE = LogLevel_MAX + 1;

const ::google::protobuf::EnumDescriptor* LogLevel_descriptor();
inline const ::std::string& LogLevel_Name(LogLevel value) {
  return ::google::protobuf::internal::NameOfEnum(
    LogLevel_descriptor(), value);
}
inline bool LogLevel_Parse(
    const ::std::string& name, LogLevel* value) {
  return ::google::protobuf::internal::ParseNamedEnum<LogLevel>(
    LogLevel_descriptor(), name, value);
}
enum Type {
  GENERIC = 0,
  PLAY_TRACK_DEVICE = 1,
  PAUSE_DEVICE = 2,
  RESUME_DEVICE = 3,
  STOP_DEVICE = 4,
  WHO_DEVICE = 5,
  WHAT_DEVICE = 6,
  TRACK_COUNT = 7,
  ARTIST_COUNT = 8,
  FOLDER_COUNT = 9,
  SELECT_QUERY = 10,
  RESERVED_01 = 11,
  WHEN_DEVICE = 12,
  CLEAR_DEVICE = 13,
  SELECT_RESULT = 14,
  ROW = 15,
  ONE_INT = 16,
  ONE_STRING = 17,
  ONE_FLOAT = 18,
  DAC_INFO_COMMAND = 19,
  NEXT_DEVICE = 20,
  COPY_QUEUE = 21,
  MOVE_QUEUE = 22,
  APPEND_QUEUE = 23,
  LOG_LEVEL = 24,
  LOG_LEVEL_QUERY = 25,
  Type_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Type_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Type_IsValid(int value);
const Type Type_MIN = GENERIC;
const Type Type_MAX = LOG_LEVEL_QUERY;
const int Type_ARRAYSIZE = Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* Type_descriptor();
inline const ::std::string& Type_Name(Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    Type_descriptor(), value);
}
inline bool Type_Parse(
    const ::std::string& name, Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Type>(
    Type_descriptor(), name, value);
}
// ===================================================================


// -------------------------------------------------------------------

class Row : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pas.Row) */ {
 public:
  Row();
  virtual ~Row();

  Row(const Row& from);

  inline Row& operator=(const Row& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Row& default_instance();

  static inline const Row* internal_default_instance() {
    return reinterpret_cast<const Row*>(
               &_Row_default_instance_);
  }

  void Swap(Row* other);

  // implements Message ----------------------------------------------

  inline Row* New() const PROTOBUF_FINAL { return New(NULL); }

  Row* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Row& from);
  void MergeFrom(const Row& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Row* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, string> results = 2;
  int results_size() const;
  void clear_results();
  static const int kResultsFieldNumber = 2;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      results() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_results();

  // .pas.Type type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::pas::Type type() const;
  void set_type(::pas::Type value);

  // @@protoc_insertion_point(class_scope:pas.Row)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  typedef ::google::protobuf::internal::MapEntryLite<
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 >
      Row_ResultsEntry;
  ::google::protobuf::internal::MapField<
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > results_;
  int type_;
  mutable int _cached_size_;
  friend struct protobuf_commands_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DacInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pas.DacInfo) */ {
 public:
  DacInfo();
  virtual ~DacInfo();

  DacInfo(const DacInfo& from);

  inline DacInfo& operator=(const DacInfo& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DacInfo& default_instance();

  static inline const DacInfo* internal_default_instance() {
    return reinterpret_cast<const DacInfo*>(
               &_DacInfo_default_instance_);
  }

  void Swap(DacInfo* other);

  // implements Message ----------------------------------------------

  inline DacInfo* New() const PROTOBUF_FINAL { return New(NULL); }

  DacInfo* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const DacInfo& from);
  void MergeFrom(const DacInfo& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(DacInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .pas.Row row = 2;
  int row_size() const;
  void clear_row();
  static const int kRowFieldNumber = 2;
  const ::pas::Row& row(int index) const;
  ::pas::Row* mutable_row(int index);
  ::pas::Row* add_row();
  ::google::protobuf::RepeatedPtrField< ::pas::Row >*
      mutable_row();
  const ::google::protobuf::RepeatedPtrField< ::pas::Row >&
      row() const;

  // .pas.Type type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::pas::Type type() const;
  void set_type(::pas::Type value);

  // @@protoc_insertion_point(class_scope:pas.DacInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::pas::Row > row_;
  int type_;
  mutable int _cached_size_;
  friend struct protobuf_commands_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SelectResult : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pas.SelectResult) */ {
 public:
  SelectResult();
  virtual ~SelectResult();

  SelectResult(const SelectResult& from);

  inline SelectResult& operator=(const SelectResult& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SelectResult& default_instance();

  static inline const SelectResult* internal_default_instance() {
    return reinterpret_cast<const SelectResult*>(
               &_SelectResult_default_instance_);
  }

  void Swap(SelectResult* other);

  // implements Message ----------------------------------------------

  inline SelectResult* New() const PROTOBUF_FINAL { return New(NULL); }

  SelectResult* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SelectResult& from);
  void MergeFrom(const SelectResult& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SelectResult* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .pas.Row row = 2;
  int row_size() const;
  void clear_row();
  static const int kRowFieldNumber = 2;
  const ::pas::Row& row(int index) const;
  ::pas::Row* mutable_row(int index);
  ::pas::Row* add_row();
  ::google::protobuf::RepeatedPtrField< ::pas::Row >*
      mutable_row();
  const ::google::protobuf::RepeatedPtrField< ::pas::Row >&
      row() const;

  // .pas.Type type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::pas::Type type() const;
  void set_type(::pas::Type value);

  // @@protoc_insertion_point(class_scope:pas.SelectResult)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::pas::Row > row_;
  int type_;
  mutable int _cached_size_;
  friend struct protobuf_commands_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GenericPB : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pas.GenericPB) */ {
 public:
  GenericPB();
  virtual ~GenericPB();

  GenericPB(const GenericPB& from);

  inline GenericPB& operator=(const GenericPB& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GenericPB& default_instance();

  static inline const GenericPB* internal_default_instance() {
    return reinterpret_cast<const GenericPB*>(
               &_GenericPB_default_instance_);
  }

  void Swap(GenericPB* other);

  // implements Message ----------------------------------------------

  inline GenericPB* New() const PROTOBUF_FINAL { return New(NULL); }

  GenericPB* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GenericPB& from);
  void MergeFrom(const GenericPB& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GenericPB* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .pas.Type type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::pas::Type type() const;
  void set_type(::pas::Type value);

  // @@protoc_insertion_point(class_scope:pas.GenericPB)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  int type_;
  mutable int _cached_size_;
  friend struct protobuf_commands_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PlayTrackCommand : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pas.PlayTrackCommand) */ {
 public:
  PlayTrackCommand();
  virtual ~PlayTrackCommand();

  PlayTrackCommand(const PlayTrackCommand& from);

  inline PlayTrackCommand& operator=(const PlayTrackCommand& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PlayTrackCommand& default_instance();

  static inline const PlayTrackCommand* internal_default_instance() {
    return reinterpret_cast<const PlayTrackCommand*>(
               &_PlayTrackCommand_default_instance_);
  }

  void Swap(PlayTrackCommand* other);

  // implements Message ----------------------------------------------

  inline PlayTrackCommand* New() const PROTOBUF_FINAL { return New(NULL); }

  PlayTrackCommand* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PlayTrackCommand& from);
  void MergeFrom(const PlayTrackCommand& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PlayTrackCommand* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 device_id = 2;
  void clear_device_id();
  static const int kDeviceIdFieldNumber = 2;
  ::google::protobuf::uint64 device_id() const;
  void set_device_id(::google::protobuf::uint64 value);

  // uint64 track_id = 3;
  void clear_track_id();
  static const int kTrackIdFieldNumber = 3;
  ::google::protobuf::uint64 track_id() const;
  void set_track_id(::google::protobuf::uint64 value);

  // .pas.Type type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::pas::Type type() const;
  void set_type(::pas::Type value);

  // @@protoc_insertion_point(class_scope:pas.PlayTrackCommand)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 device_id_;
  ::google::protobuf::uint64 track_id_;
  int type_;
  mutable int _cached_size_;
  friend struct protobuf_commands_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PauseDeviceCommand : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pas.PauseDeviceCommand) */ {
 public:
  PauseDeviceCommand();
  virtual ~PauseDeviceCommand();

  PauseDeviceCommand(const PauseDeviceCommand& from);

  inline PauseDeviceCommand& operator=(const PauseDeviceCommand& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PauseDeviceCommand& default_instance();

  static inline const PauseDeviceCommand* internal_default_instance() {
    return reinterpret_cast<const PauseDeviceCommand*>(
               &_PauseDeviceCommand_default_instance_);
  }

  void Swap(PauseDeviceCommand* other);

  // implements Message ----------------------------------------------

  inline PauseDeviceCommand* New() const PROTOBUF_FINAL { return New(NULL); }

  PauseDeviceCommand* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PauseDeviceCommand& from);
  void MergeFrom(const PauseDeviceCommand& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PauseDeviceCommand* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 device_id = 2;
  void clear_device_id();
  static const int kDeviceIdFieldNumber = 2;
  ::google::protobuf::uint64 device_id() const;
  void set_device_id(::google::protobuf::uint64 value);

  // .pas.Type type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::pas::Type type() const;
  void set_type(::pas::Type value);

  // @@protoc_insertion_point(class_scope:pas.PauseDeviceCommand)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 device_id_;
  int type_;
  mutable int _cached_size_;
  friend struct protobuf_commands_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ResumeDeviceCommand : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pas.ResumeDeviceCommand) */ {
 public:
  ResumeDeviceCommand();
  virtual ~ResumeDeviceCommand();

  ResumeDeviceCommand(const ResumeDeviceCommand& from);

  inline ResumeDeviceCommand& operator=(const ResumeDeviceCommand& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ResumeDeviceCommand& default_instance();

  static inline const ResumeDeviceCommand* internal_default_instance() {
    return reinterpret_cast<const ResumeDeviceCommand*>(
               &_ResumeDeviceCommand_default_instance_);
  }

  void Swap(ResumeDeviceCommand* other);

  // implements Message ----------------------------------------------

  inline ResumeDeviceCommand* New() const PROTOBUF_FINAL { return New(NULL); }

  ResumeDeviceCommand* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ResumeDeviceCommand& from);
  void MergeFrom(const ResumeDeviceCommand& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ResumeDeviceCommand* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 device_id = 2;
  void clear_device_id();
  static const int kDeviceIdFieldNumber = 2;
  ::google::protobuf::uint64 device_id() const;
  void set_device_id(::google::protobuf::uint64 value);

  // .pas.Type type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::pas::Type type() const;
  void set_type(::pas::Type value);

  // @@protoc_insertion_point(class_scope:pas.ResumeDeviceCommand)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 device_id_;
  int type_;
  mutable int _cached_size_;
  friend struct protobuf_commands_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ClearDeviceCommand : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pas.ClearDeviceCommand) */ {
 public:
  ClearDeviceCommand();
  virtual ~ClearDeviceCommand();

  ClearDeviceCommand(const ClearDeviceCommand& from);

  inline ClearDeviceCommand& operator=(const ClearDeviceCommand& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ClearDeviceCommand& default_instance();

  static inline const ClearDeviceCommand* internal_default_instance() {
    return reinterpret_cast<const ClearDeviceCommand*>(
               &_ClearDeviceCommand_default_instance_);
  }

  void Swap(ClearDeviceCommand* other);

  // implements Message ----------------------------------------------

  inline ClearDeviceCommand* New() const PROTOBUF_FINAL { return New(NULL); }

  ClearDeviceCommand* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ClearDeviceCommand& from);
  void MergeFrom(const ClearDeviceCommand& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ClearDeviceCommand* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 device_id = 2;
  void clear_device_id();
  static const int kDeviceIdFieldNumber = 2;
  ::google::protobuf::uint64 device_id() const;
  void set_device_id(::google::protobuf::uint64 value);

  // .pas.Type type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::pas::Type type() const;
  void set_type(::pas::Type value);

  // @@protoc_insertion_point(class_scope:pas.ClearDeviceCommand)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 device_id_;
  int type_;
  mutable int _cached_size_;
  friend struct protobuf_commands_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class StopDeviceCommand : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pas.StopDeviceCommand) */ {
 public:
  StopDeviceCommand();
  virtual ~StopDeviceCommand();

  StopDeviceCommand(const StopDeviceCommand& from);

  inline StopDeviceCommand& operator=(const StopDeviceCommand& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StopDeviceCommand& default_instance();

  static inline const StopDeviceCommand* internal_default_instance() {
    return reinterpret_cast<const StopDeviceCommand*>(
               &_StopDeviceCommand_default_instance_);
  }

  void Swap(StopDeviceCommand* other);

  // implements Message ----------------------------------------------

  inline StopDeviceCommand* New() const PROTOBUF_FINAL { return New(NULL); }

  StopDeviceCommand* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const StopDeviceCommand& from);
  void MergeFrom(const StopDeviceCommand& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(StopDeviceCommand* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 device_id = 2;
  void clear_device_id();
  static const int kDeviceIdFieldNumber = 2;
  ::google::protobuf::uint64 device_id() const;
  void set_device_id(::google::protobuf::uint64 value);

  // .pas.Type type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::pas::Type type() const;
  void set_type(::pas::Type value);

  // @@protoc_insertion_point(class_scope:pas.StopDeviceCommand)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 device_id_;
  int type_;
  mutable int _cached_size_;
  friend struct protobuf_commands_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class WhoDeviceCommand : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pas.WhoDeviceCommand) */ {
 public:
  WhoDeviceCommand();
  virtual ~WhoDeviceCommand();

  WhoDeviceCommand(const WhoDeviceCommand& from);

  inline WhoDeviceCommand& operator=(const WhoDeviceCommand& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WhoDeviceCommand& default_instance();

  static inline const WhoDeviceCommand* internal_default_instance() {
    return reinterpret_cast<const WhoDeviceCommand*>(
               &_WhoDeviceCommand_default_instance_);
  }

  void Swap(WhoDeviceCommand* other);

  // implements Message ----------------------------------------------

  inline WhoDeviceCommand* New() const PROTOBUF_FINAL { return New(NULL); }

  WhoDeviceCommand* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const WhoDeviceCommand& from);
  void MergeFrom(const WhoDeviceCommand& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(WhoDeviceCommand* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 device_id = 2;
  void clear_device_id();
  static const int kDeviceIdFieldNumber = 2;
  ::google::protobuf::uint64 device_id() const;
  void set_device_id(::google::protobuf::uint64 value);

  // .pas.Type type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::pas::Type type() const;
  void set_type(::pas::Type value);

  // @@protoc_insertion_point(class_scope:pas.WhoDeviceCommand)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 device_id_;
  int type_;
  mutable int _cached_size_;
  friend struct protobuf_commands_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class WhatDeviceCommand : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pas.WhatDeviceCommand) */ {
 public:
  WhatDeviceCommand();
  virtual ~WhatDeviceCommand();

  WhatDeviceCommand(const WhatDeviceCommand& from);

  inline WhatDeviceCommand& operator=(const WhatDeviceCommand& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WhatDeviceCommand& default_instance();

  static inline const WhatDeviceCommand* internal_default_instance() {
    return reinterpret_cast<const WhatDeviceCommand*>(
               &_WhatDeviceCommand_default_instance_);
  }

  void Swap(WhatDeviceCommand* other);

  // implements Message ----------------------------------------------

  inline WhatDeviceCommand* New() const PROTOBUF_FINAL { return New(NULL); }

  WhatDeviceCommand* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const WhatDeviceCommand& from);
  void MergeFrom(const WhatDeviceCommand& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(WhatDeviceCommand* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 device_id = 2;
  void clear_device_id();
  static const int kDeviceIdFieldNumber = 2;
  ::google::protobuf::uint64 device_id() const;
  void set_device_id(::google::protobuf::uint64 value);

  // .pas.Type type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::pas::Type type() const;
  void set_type(::pas::Type value);

  // @@protoc_insertion_point(class_scope:pas.WhatDeviceCommand)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 device_id_;
  int type_;
  mutable int _cached_size_;
  friend struct protobuf_commands_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class TrackCountQuery : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pas.TrackCountQuery) */ {
 public:
  TrackCountQuery();
  virtual ~TrackCountQuery();

  TrackCountQuery(const TrackCountQuery& from);

  inline TrackCountQuery& operator=(const TrackCountQuery& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TrackCountQuery& default_instance();

  static inline const TrackCountQuery* internal_default_instance() {
    return reinterpret_cast<const TrackCountQuery*>(
               &_TrackCountQuery_default_instance_);
  }

  void Swap(TrackCountQuery* other);

  // implements Message ----------------------------------------------

  inline TrackCountQuery* New() const PROTOBUF_FINAL { return New(NULL); }

  TrackCountQuery* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TrackCountQuery& from);
  void MergeFrom(const TrackCountQuery& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TrackCountQuery* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .pas.Type type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::pas::Type type() const;
  void set_type(::pas::Type value);

  // @@protoc_insertion_point(class_scope:pas.TrackCountQuery)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  int type_;
  mutable int _cached_size_;
  friend struct protobuf_commands_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ArtistCountQuery : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pas.ArtistCountQuery) */ {
 public:
  ArtistCountQuery();
  virtual ~ArtistCountQuery();

  ArtistCountQuery(const ArtistCountQuery& from);

  inline ArtistCountQuery& operator=(const ArtistCountQuery& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ArtistCountQuery& default_instance();

  static inline const ArtistCountQuery* internal_default_instance() {
    return reinterpret_cast<const ArtistCountQuery*>(
               &_ArtistCountQuery_default_instance_);
  }

  void Swap(ArtistCountQuery* other);

  // implements Message ----------------------------------------------

  inline ArtistCountQuery* New() const PROTOBUF_FINAL { return New(NULL); }

  ArtistCountQuery* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ArtistCountQuery& from);
  void MergeFrom(const ArtistCountQuery& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ArtistCountQuery* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .pas.Type type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::pas::Type type() const;
  void set_type(::pas::Type value);

  // @@protoc_insertion_point(class_scope:pas.ArtistCountQuery)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  int type_;
  mutable int _cached_size_;
  friend struct protobuf_commands_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class FolderCountQuery : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pas.FolderCountQuery) */ {
 public:
  FolderCountQuery();
  virtual ~FolderCountQuery();

  FolderCountQuery(const FolderCountQuery& from);

  inline FolderCountQuery& operator=(const FolderCountQuery& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FolderCountQuery& default_instance();

  static inline const FolderCountQuery* internal_default_instance() {
    return reinterpret_cast<const FolderCountQuery*>(
               &_FolderCountQuery_default_instance_);
  }

  void Swap(FolderCountQuery* other);

  // implements Message ----------------------------------------------

  inline FolderCountQuery* New() const PROTOBUF_FINAL { return New(NULL); }

  FolderCountQuery* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const FolderCountQuery& from);
  void MergeFrom(const FolderCountQuery& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(FolderCountQuery* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .pas.Type type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::pas::Type type() const;
  void set_type(::pas::Type value);

  // @@protoc_insertion_point(class_scope:pas.FolderCountQuery)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  int type_;
  mutable int _cached_size_;
  friend struct protobuf_commands_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SelectQuery : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pas.SelectQuery) */ {
 public:
  SelectQuery();
  virtual ~SelectQuery();

  SelectQuery(const SelectQuery& from);

  inline SelectQuery& operator=(const SelectQuery& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SelectQuery& default_instance();

  static inline const SelectQuery* internal_default_instance() {
    return reinterpret_cast<const SelectQuery*>(
               &_SelectQuery_default_instance_);
  }

  void Swap(SelectQuery* other);

  // implements Message ----------------------------------------------

  inline SelectQuery* New() const PROTOBUF_FINAL { return New(NULL); }

  SelectQuery* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SelectQuery& from);
  void MergeFrom(const SelectQuery& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SelectQuery* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string column = 2;
  void clear_column();
  static const int kColumnFieldNumber = 2;
  const ::std::string& column() const;
  void set_column(const ::std::string& value);
  #if LANG_CXX11
  void set_column(::std::string&& value);
  #endif
  void set_column(const char* value);
  void set_column(const char* value, size_t size);
  ::std::string* mutable_column();
  ::std::string* release_column();
  void set_allocated_column(::std::string* column);

  // string pattern = 3;
  void clear_pattern();
  static const int kPatternFieldNumber = 3;
  const ::std::string& pattern() const;
  void set_pattern(const ::std::string& value);
  #if LANG_CXX11
  void set_pattern(::std::string&& value);
  #endif
  void set_pattern(const char* value);
  void set_pattern(const char* value, size_t size);
  ::std::string* mutable_pattern();
  ::std::string* release_pattern();
  void set_allocated_pattern(::std::string* pattern);

  // .pas.Type type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::pas::Type type() const;
  void set_type(::pas::Type value);

  // @@protoc_insertion_point(class_scope:pas.SelectQuery)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr column_;
  ::google::protobuf::internal::ArenaStringPtr pattern_;
  int type_;
  mutable int _cached_size_;
  friend struct protobuf_commands_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class WhenDeviceCommand : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pas.WhenDeviceCommand) */ {
 public:
  WhenDeviceCommand();
  virtual ~WhenDeviceCommand();

  WhenDeviceCommand(const WhenDeviceCommand& from);

  inline WhenDeviceCommand& operator=(const WhenDeviceCommand& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WhenDeviceCommand& default_instance();

  static inline const WhenDeviceCommand* internal_default_instance() {
    return reinterpret_cast<const WhenDeviceCommand*>(
               &_WhenDeviceCommand_default_instance_);
  }

  void Swap(WhenDeviceCommand* other);

  // implements Message ----------------------------------------------

  inline WhenDeviceCommand* New() const PROTOBUF_FINAL { return New(NULL); }

  WhenDeviceCommand* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const WhenDeviceCommand& from);
  void MergeFrom(const WhenDeviceCommand& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(WhenDeviceCommand* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 device_id = 2;
  void clear_device_id();
  static const int kDeviceIdFieldNumber = 2;
  ::google::protobuf::uint64 device_id() const;
  void set_device_id(::google::protobuf::uint64 value);

  // .pas.Type type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::pas::Type type() const;
  void set_type(::pas::Type value);

  // @@protoc_insertion_point(class_scope:pas.WhenDeviceCommand)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 device_id_;
  int type_;
  mutable int _cached_size_;
  friend struct protobuf_commands_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class OneInteger : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pas.OneInteger) */ {
 public:
  OneInteger();
  virtual ~OneInteger();

  OneInteger(const OneInteger& from);

  inline OneInteger& operator=(const OneInteger& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OneInteger& default_instance();

  static inline const OneInteger* internal_default_instance() {
    return reinterpret_cast<const OneInteger*>(
               &_OneInteger_default_instance_);
  }

  void Swap(OneInteger* other);

  // implements Message ----------------------------------------------

  inline OneInteger* New() const PROTOBUF_FINAL { return New(NULL); }

  OneInteger* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const OneInteger& from);
  void MergeFrom(const OneInteger& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(OneInteger* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 value = 2;
  void clear_value();
  static const int kValueFieldNumber = 2;
  ::google::protobuf::uint64 value() const;
  void set_value(::google::protobuf::uint64 value);

  // .pas.Type type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::pas::Type type() const;
  void set_type(::pas::Type value);

  // @@protoc_insertion_point(class_scope:pas.OneInteger)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 value_;
  int type_;
  mutable int _cached_size_;
  friend struct protobuf_commands_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class OneString : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pas.OneString) */ {
 public:
  OneString();
  virtual ~OneString();

  OneString(const OneString& from);

  inline OneString& operator=(const OneString& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OneString& default_instance();

  static inline const OneString* internal_default_instance() {
    return reinterpret_cast<const OneString*>(
               &_OneString_default_instance_);
  }

  void Swap(OneString* other);

  // implements Message ----------------------------------------------

  inline OneString* New() const PROTOBUF_FINAL { return New(NULL); }

  OneString* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const OneString& from);
  void MergeFrom(const OneString& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(OneString* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string value = 2;
  void clear_value();
  static const int kValueFieldNumber = 2;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  #if LANG_CXX11
  void set_value(::std::string&& value);
  #endif
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // .pas.Type type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::pas::Type type() const;
  void set_type(::pas::Type value);

  // @@protoc_insertion_point(class_scope:pas.OneString)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  int type_;
  mutable int _cached_size_;
  friend struct protobuf_commands_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class OneFloat : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pas.OneFloat) */ {
 public:
  OneFloat();
  virtual ~OneFloat();

  OneFloat(const OneFloat& from);

  inline OneFloat& operator=(const OneFloat& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OneFloat& default_instance();

  static inline const OneFloat* internal_default_instance() {
    return reinterpret_cast<const OneFloat*>(
               &_OneFloat_default_instance_);
  }

  void Swap(OneFloat* other);

  // implements Message ----------------------------------------------

  inline OneFloat* New() const PROTOBUF_FINAL { return New(NULL); }

  OneFloat* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const OneFloat& from);
  void MergeFrom(const OneFloat& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(OneFloat* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .pas.Type type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::pas::Type type() const;
  void set_type(::pas::Type value);

  // float value = 2;
  void clear_value();
  static const int kValueFieldNumber = 2;
  float value() const;
  void set_value(float value);

  // @@protoc_insertion_point(class_scope:pas.OneFloat)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  int type_;
  float value_;
  mutable int _cached_size_;
  friend struct protobuf_commands_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class TwoIntegers : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pas.TwoIntegers) */ {
 public:
  TwoIntegers();
  virtual ~TwoIntegers();

  TwoIntegers(const TwoIntegers& from);

  inline TwoIntegers& operator=(const TwoIntegers& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TwoIntegers& default_instance();

  static inline const TwoIntegers* internal_default_instance() {
    return reinterpret_cast<const TwoIntegers*>(
               &_TwoIntegers_default_instance_);
  }

  void Swap(TwoIntegers* other);

  // implements Message ----------------------------------------------

  inline TwoIntegers* New() const PROTOBUF_FINAL { return New(NULL); }

  TwoIntegers* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TwoIntegers& from);
  void MergeFrom(const TwoIntegers& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TwoIntegers* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 value_a = 2;
  void clear_value_a();
  static const int kValueAFieldNumber = 2;
  ::google::protobuf::uint64 value_a() const;
  void set_value_a(::google::protobuf::uint64 value);

  // uint64 value_b = 3;
  void clear_value_b();
  static const int kValueBFieldNumber = 3;
  ::google::protobuf::uint64 value_b() const;
  void set_value_b(::google::protobuf::uint64 value);

  // .pas.Type type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::pas::Type type() const;
  void set_type(::pas::Type value);

  // @@protoc_insertion_point(class_scope:pas.TwoIntegers)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 value_a_;
  ::google::protobuf::uint64 value_b_;
  int type_;
  mutable int _cached_size_;
  friend struct protobuf_commands_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// Row

// .pas.Type type = 1;
inline void Row::clear_type() {
  type_ = 0;
}
inline ::pas::Type Row::type() const {
  // @@protoc_insertion_point(field_get:pas.Row.type)
  return static_cast< ::pas::Type >(type_);
}
inline void Row::set_type(::pas::Type value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:pas.Row.type)
}

// map<string, string> results = 2;
inline int Row::results_size() const {
  return results_.size();
}
inline void Row::clear_results() {
  results_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
Row::results() const {
  // @@protoc_insertion_point(field_map:pas.Row.results)
  return results_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
Row::mutable_results() {
  // @@protoc_insertion_point(field_mutable_map:pas.Row.results)
  return results_.MutableMap();
}

// -------------------------------------------------------------------

// DacInfo

// .pas.Type type = 1;
inline void DacInfo::clear_type() {
  type_ = 0;
}
inline ::pas::Type DacInfo::type() const {
  // @@protoc_insertion_point(field_get:pas.DacInfo.type)
  return static_cast< ::pas::Type >(type_);
}
inline void DacInfo::set_type(::pas::Type value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:pas.DacInfo.type)
}

// repeated .pas.Row row = 2;
inline int DacInfo::row_size() const {
  return row_.size();
}
inline void DacInfo::clear_row() {
  row_.Clear();
}
inline const ::pas::Row& DacInfo::row(int index) const {
  // @@protoc_insertion_point(field_get:pas.DacInfo.row)
  return row_.Get(index);
}
inline ::pas::Row* DacInfo::mutable_row(int index) {
  // @@protoc_insertion_point(field_mutable:pas.DacInfo.row)
  return row_.Mutable(index);
}
inline ::pas::Row* DacInfo::add_row() {
  // @@protoc_insertion_point(field_add:pas.DacInfo.row)
  return row_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::pas::Row >*
DacInfo::mutable_row() {
  // @@protoc_insertion_point(field_mutable_list:pas.DacInfo.row)
  return &row_;
}
inline const ::google::protobuf::RepeatedPtrField< ::pas::Row >&
DacInfo::row() const {
  // @@protoc_insertion_point(field_list:pas.DacInfo.row)
  return row_;
}

// -------------------------------------------------------------------

// SelectResult

// .pas.Type type = 1;
inline void SelectResult::clear_type() {
  type_ = 0;
}
inline ::pas::Type SelectResult::type() const {
  // @@protoc_insertion_point(field_get:pas.SelectResult.type)
  return static_cast< ::pas::Type >(type_);
}
inline void SelectResult::set_type(::pas::Type value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:pas.SelectResult.type)
}

// repeated .pas.Row row = 2;
inline int SelectResult::row_size() const {
  return row_.size();
}
inline void SelectResult::clear_row() {
  row_.Clear();
}
inline const ::pas::Row& SelectResult::row(int index) const {
  // @@protoc_insertion_point(field_get:pas.SelectResult.row)
  return row_.Get(index);
}
inline ::pas::Row* SelectResult::mutable_row(int index) {
  // @@protoc_insertion_point(field_mutable:pas.SelectResult.row)
  return row_.Mutable(index);
}
inline ::pas::Row* SelectResult::add_row() {
  // @@protoc_insertion_point(field_add:pas.SelectResult.row)
  return row_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::pas::Row >*
SelectResult::mutable_row() {
  // @@protoc_insertion_point(field_mutable_list:pas.SelectResult.row)
  return &row_;
}
inline const ::google::protobuf::RepeatedPtrField< ::pas::Row >&
SelectResult::row() const {
  // @@protoc_insertion_point(field_list:pas.SelectResult.row)
  return row_;
}

// -------------------------------------------------------------------

// GenericPB

// .pas.Type type = 1;
inline void GenericPB::clear_type() {
  type_ = 0;
}
inline ::pas::Type GenericPB::type() const {
  // @@protoc_insertion_point(field_get:pas.GenericPB.type)
  return static_cast< ::pas::Type >(type_);
}
inline void GenericPB::set_type(::pas::Type value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:pas.GenericPB.type)
}

// -------------------------------------------------------------------

// PlayTrackCommand

// .pas.Type type = 1;
inline void PlayTrackCommand::clear_type() {
  type_ = 0;
}
inline ::pas::Type PlayTrackCommand::type() const {
  // @@protoc_insertion_point(field_get:pas.PlayTrackCommand.type)
  return static_cast< ::pas::Type >(type_);
}
inline void PlayTrackCommand::set_type(::pas::Type value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:pas.PlayTrackCommand.type)
}

// uint64 device_id = 2;
inline void PlayTrackCommand::clear_device_id() {
  device_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PlayTrackCommand::device_id() const {
  // @@protoc_insertion_point(field_get:pas.PlayTrackCommand.device_id)
  return device_id_;
}
inline void PlayTrackCommand::set_device_id(::google::protobuf::uint64 value) {
  
  device_id_ = value;
  // @@protoc_insertion_point(field_set:pas.PlayTrackCommand.device_id)
}

// uint64 track_id = 3;
inline void PlayTrackCommand::clear_track_id() {
  track_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PlayTrackCommand::track_id() const {
  // @@protoc_insertion_point(field_get:pas.PlayTrackCommand.track_id)
  return track_id_;
}
inline void PlayTrackCommand::set_track_id(::google::protobuf::uint64 value) {
  
  track_id_ = value;
  // @@protoc_insertion_point(field_set:pas.PlayTrackCommand.track_id)
}

// -------------------------------------------------------------------

// PauseDeviceCommand

// .pas.Type type = 1;
inline void PauseDeviceCommand::clear_type() {
  type_ = 0;
}
inline ::pas::Type PauseDeviceCommand::type() const {
  // @@protoc_insertion_point(field_get:pas.PauseDeviceCommand.type)
  return static_cast< ::pas::Type >(type_);
}
inline void PauseDeviceCommand::set_type(::pas::Type value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:pas.PauseDeviceCommand.type)
}

// uint64 device_id = 2;
inline void PauseDeviceCommand::clear_device_id() {
  device_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PauseDeviceCommand::device_id() const {
  // @@protoc_insertion_point(field_get:pas.PauseDeviceCommand.device_id)
  return device_id_;
}
inline void PauseDeviceCommand::set_device_id(::google::protobuf::uint64 value) {
  
  device_id_ = value;
  // @@protoc_insertion_point(field_set:pas.PauseDeviceCommand.device_id)
}

// -------------------------------------------------------------------

// ResumeDeviceCommand

// .pas.Type type = 1;
inline void ResumeDeviceCommand::clear_type() {
  type_ = 0;
}
inline ::pas::Type ResumeDeviceCommand::type() const {
  // @@protoc_insertion_point(field_get:pas.ResumeDeviceCommand.type)
  return static_cast< ::pas::Type >(type_);
}
inline void ResumeDeviceCommand::set_type(::pas::Type value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:pas.ResumeDeviceCommand.type)
}

// uint64 device_id = 2;
inline void ResumeDeviceCommand::clear_device_id() {
  device_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ResumeDeviceCommand::device_id() const {
  // @@protoc_insertion_point(field_get:pas.ResumeDeviceCommand.device_id)
  return device_id_;
}
inline void ResumeDeviceCommand::set_device_id(::google::protobuf::uint64 value) {
  
  device_id_ = value;
  // @@protoc_insertion_point(field_set:pas.ResumeDeviceCommand.device_id)
}

// -------------------------------------------------------------------

// ClearDeviceCommand

// .pas.Type type = 1;
inline void ClearDeviceCommand::clear_type() {
  type_ = 0;
}
inline ::pas::Type ClearDeviceCommand::type() const {
  // @@protoc_insertion_point(field_get:pas.ClearDeviceCommand.type)
  return static_cast< ::pas::Type >(type_);
}
inline void ClearDeviceCommand::set_type(::pas::Type value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:pas.ClearDeviceCommand.type)
}

// uint64 device_id = 2;
inline void ClearDeviceCommand::clear_device_id() {
  device_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ClearDeviceCommand::device_id() const {
  // @@protoc_insertion_point(field_get:pas.ClearDeviceCommand.device_id)
  return device_id_;
}
inline void ClearDeviceCommand::set_device_id(::google::protobuf::uint64 value) {
  
  device_id_ = value;
  // @@protoc_insertion_point(field_set:pas.ClearDeviceCommand.device_id)
}

// -------------------------------------------------------------------

// StopDeviceCommand

// .pas.Type type = 1;
inline void StopDeviceCommand::clear_type() {
  type_ = 0;
}
inline ::pas::Type StopDeviceCommand::type() const {
  // @@protoc_insertion_point(field_get:pas.StopDeviceCommand.type)
  return static_cast< ::pas::Type >(type_);
}
inline void StopDeviceCommand::set_type(::pas::Type value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:pas.StopDeviceCommand.type)
}

// uint64 device_id = 2;
inline void StopDeviceCommand::clear_device_id() {
  device_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 StopDeviceCommand::device_id() const {
  // @@protoc_insertion_point(field_get:pas.StopDeviceCommand.device_id)
  return device_id_;
}
inline void StopDeviceCommand::set_device_id(::google::protobuf::uint64 value) {
  
  device_id_ = value;
  // @@protoc_insertion_point(field_set:pas.StopDeviceCommand.device_id)
}

// -------------------------------------------------------------------

// WhoDeviceCommand

// .pas.Type type = 1;
inline void WhoDeviceCommand::clear_type() {
  type_ = 0;
}
inline ::pas::Type WhoDeviceCommand::type() const {
  // @@protoc_insertion_point(field_get:pas.WhoDeviceCommand.type)
  return static_cast< ::pas::Type >(type_);
}
inline void WhoDeviceCommand::set_type(::pas::Type value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:pas.WhoDeviceCommand.type)
}

// uint64 device_id = 2;
inline void WhoDeviceCommand::clear_device_id() {
  device_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 WhoDeviceCommand::device_id() const {
  // @@protoc_insertion_point(field_get:pas.WhoDeviceCommand.device_id)
  return device_id_;
}
inline void WhoDeviceCommand::set_device_id(::google::protobuf::uint64 value) {
  
  device_id_ = value;
  // @@protoc_insertion_point(field_set:pas.WhoDeviceCommand.device_id)
}

// -------------------------------------------------------------------

// WhatDeviceCommand

// .pas.Type type = 1;
inline void WhatDeviceCommand::clear_type() {
  type_ = 0;
}
inline ::pas::Type WhatDeviceCommand::type() const {
  // @@protoc_insertion_point(field_get:pas.WhatDeviceCommand.type)
  return static_cast< ::pas::Type >(type_);
}
inline void WhatDeviceCommand::set_type(::pas::Type value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:pas.WhatDeviceCommand.type)
}

// uint64 device_id = 2;
inline void WhatDeviceCommand::clear_device_id() {
  device_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 WhatDeviceCommand::device_id() const {
  // @@protoc_insertion_point(field_get:pas.WhatDeviceCommand.device_id)
  return device_id_;
}
inline void WhatDeviceCommand::set_device_id(::google::protobuf::uint64 value) {
  
  device_id_ = value;
  // @@protoc_insertion_point(field_set:pas.WhatDeviceCommand.device_id)
}

// -------------------------------------------------------------------

// TrackCountQuery

// .pas.Type type = 1;
inline void TrackCountQuery::clear_type() {
  type_ = 0;
}
inline ::pas::Type TrackCountQuery::type() const {
  // @@protoc_insertion_point(field_get:pas.TrackCountQuery.type)
  return static_cast< ::pas::Type >(type_);
}
inline void TrackCountQuery::set_type(::pas::Type value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:pas.TrackCountQuery.type)
}

// -------------------------------------------------------------------

// ArtistCountQuery

// .pas.Type type = 1;
inline void ArtistCountQuery::clear_type() {
  type_ = 0;
}
inline ::pas::Type ArtistCountQuery::type() const {
  // @@protoc_insertion_point(field_get:pas.ArtistCountQuery.type)
  return static_cast< ::pas::Type >(type_);
}
inline void ArtistCountQuery::set_type(::pas::Type value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:pas.ArtistCountQuery.type)
}

// -------------------------------------------------------------------

// FolderCountQuery

// .pas.Type type = 1;
inline void FolderCountQuery::clear_type() {
  type_ = 0;
}
inline ::pas::Type FolderCountQuery::type() const {
  // @@protoc_insertion_point(field_get:pas.FolderCountQuery.type)
  return static_cast< ::pas::Type >(type_);
}
inline void FolderCountQuery::set_type(::pas::Type value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:pas.FolderCountQuery.type)
}

// -------------------------------------------------------------------

// SelectQuery

// .pas.Type type = 1;
inline void SelectQuery::clear_type() {
  type_ = 0;
}
inline ::pas::Type SelectQuery::type() const {
  // @@protoc_insertion_point(field_get:pas.SelectQuery.type)
  return static_cast< ::pas::Type >(type_);
}
inline void SelectQuery::set_type(::pas::Type value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:pas.SelectQuery.type)
}

// string column = 2;
inline void SelectQuery::clear_column() {
  column_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SelectQuery::column() const {
  // @@protoc_insertion_point(field_get:pas.SelectQuery.column)
  return column_.GetNoArena();
}
inline void SelectQuery::set_column(const ::std::string& value) {
  
  column_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pas.SelectQuery.column)
}
#if LANG_CXX11
inline void SelectQuery::set_column(::std::string&& value) {
  
  column_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pas.SelectQuery.column)
}
#endif
inline void SelectQuery::set_column(const char* value) {
  
  column_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pas.SelectQuery.column)
}
inline void SelectQuery::set_column(const char* value, size_t size) {
  
  column_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pas.SelectQuery.column)
}
inline ::std::string* SelectQuery::mutable_column() {
  
  // @@protoc_insertion_point(field_mutable:pas.SelectQuery.column)
  return column_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SelectQuery::release_column() {
  // @@protoc_insertion_point(field_release:pas.SelectQuery.column)
  
  return column_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SelectQuery::set_allocated_column(::std::string* column) {
  if (column != NULL) {
    
  } else {
    
  }
  column_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), column);
  // @@protoc_insertion_point(field_set_allocated:pas.SelectQuery.column)
}

// string pattern = 3;
inline void SelectQuery::clear_pattern() {
  pattern_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SelectQuery::pattern() const {
  // @@protoc_insertion_point(field_get:pas.SelectQuery.pattern)
  return pattern_.GetNoArena();
}
inline void SelectQuery::set_pattern(const ::std::string& value) {
  
  pattern_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pas.SelectQuery.pattern)
}
#if LANG_CXX11
inline void SelectQuery::set_pattern(::std::string&& value) {
  
  pattern_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pas.SelectQuery.pattern)
}
#endif
inline void SelectQuery::set_pattern(const char* value) {
  
  pattern_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pas.SelectQuery.pattern)
}
inline void SelectQuery::set_pattern(const char* value, size_t size) {
  
  pattern_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pas.SelectQuery.pattern)
}
inline ::std::string* SelectQuery::mutable_pattern() {
  
  // @@protoc_insertion_point(field_mutable:pas.SelectQuery.pattern)
  return pattern_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SelectQuery::release_pattern() {
  // @@protoc_insertion_point(field_release:pas.SelectQuery.pattern)
  
  return pattern_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SelectQuery::set_allocated_pattern(::std::string* pattern) {
  if (pattern != NULL) {
    
  } else {
    
  }
  pattern_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), pattern);
  // @@protoc_insertion_point(field_set_allocated:pas.SelectQuery.pattern)
}

// -------------------------------------------------------------------

// WhenDeviceCommand

// .pas.Type type = 1;
inline void WhenDeviceCommand::clear_type() {
  type_ = 0;
}
inline ::pas::Type WhenDeviceCommand::type() const {
  // @@protoc_insertion_point(field_get:pas.WhenDeviceCommand.type)
  return static_cast< ::pas::Type >(type_);
}
inline void WhenDeviceCommand::set_type(::pas::Type value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:pas.WhenDeviceCommand.type)
}

// uint64 device_id = 2;
inline void WhenDeviceCommand::clear_device_id() {
  device_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 WhenDeviceCommand::device_id() const {
  // @@protoc_insertion_point(field_get:pas.WhenDeviceCommand.device_id)
  return device_id_;
}
inline void WhenDeviceCommand::set_device_id(::google::protobuf::uint64 value) {
  
  device_id_ = value;
  // @@protoc_insertion_point(field_set:pas.WhenDeviceCommand.device_id)
}

// -------------------------------------------------------------------

// OneInteger

// .pas.Type type = 1;
inline void OneInteger::clear_type() {
  type_ = 0;
}
inline ::pas::Type OneInteger::type() const {
  // @@protoc_insertion_point(field_get:pas.OneInteger.type)
  return static_cast< ::pas::Type >(type_);
}
inline void OneInteger::set_type(::pas::Type value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:pas.OneInteger.type)
}

// uint64 value = 2;
inline void OneInteger::clear_value() {
  value_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 OneInteger::value() const {
  // @@protoc_insertion_point(field_get:pas.OneInteger.value)
  return value_;
}
inline void OneInteger::set_value(::google::protobuf::uint64 value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:pas.OneInteger.value)
}

// -------------------------------------------------------------------

// OneString

// .pas.Type type = 1;
inline void OneString::clear_type() {
  type_ = 0;
}
inline ::pas::Type OneString::type() const {
  // @@protoc_insertion_point(field_get:pas.OneString.type)
  return static_cast< ::pas::Type >(type_);
}
inline void OneString::set_type(::pas::Type value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:pas.OneString.type)
}

// string value = 2;
inline void OneString::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& OneString::value() const {
  // @@protoc_insertion_point(field_get:pas.OneString.value)
  return value_.GetNoArena();
}
inline void OneString::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pas.OneString.value)
}
#if LANG_CXX11
inline void OneString::set_value(::std::string&& value) {
  
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pas.OneString.value)
}
#endif
inline void OneString::set_value(const char* value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pas.OneString.value)
}
inline void OneString::set_value(const char* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pas.OneString.value)
}
inline ::std::string* OneString::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:pas.OneString.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* OneString::release_value() {
  // @@protoc_insertion_point(field_release:pas.OneString.value)
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void OneString::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:pas.OneString.value)
}

// -------------------------------------------------------------------

// OneFloat

// .pas.Type type = 1;
inline void OneFloat::clear_type() {
  type_ = 0;
}
inline ::pas::Type OneFloat::type() const {
  // @@protoc_insertion_point(field_get:pas.OneFloat.type)
  return static_cast< ::pas::Type >(type_);
}
inline void OneFloat::set_type(::pas::Type value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:pas.OneFloat.type)
}

// float value = 2;
inline void OneFloat::clear_value() {
  value_ = 0;
}
inline float OneFloat::value() const {
  // @@protoc_insertion_point(field_get:pas.OneFloat.value)
  return value_;
}
inline void OneFloat::set_value(float value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:pas.OneFloat.value)
}

// -------------------------------------------------------------------

// TwoIntegers

// .pas.Type type = 1;
inline void TwoIntegers::clear_type() {
  type_ = 0;
}
inline ::pas::Type TwoIntegers::type() const {
  // @@protoc_insertion_point(field_get:pas.TwoIntegers.type)
  return static_cast< ::pas::Type >(type_);
}
inline void TwoIntegers::set_type(::pas::Type value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:pas.TwoIntegers.type)
}

// uint64 value_a = 2;
inline void TwoIntegers::clear_value_a() {
  value_a_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 TwoIntegers::value_a() const {
  // @@protoc_insertion_point(field_get:pas.TwoIntegers.value_a)
  return value_a_;
}
inline void TwoIntegers::set_value_a(::google::protobuf::uint64 value) {
  
  value_a_ = value;
  // @@protoc_insertion_point(field_set:pas.TwoIntegers.value_a)
}

// uint64 value_b = 3;
inline void TwoIntegers::clear_value_b() {
  value_b_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 TwoIntegers::value_b() const {
  // @@protoc_insertion_point(field_get:pas.TwoIntegers.value_b)
  return value_b_;
}
inline void TwoIntegers::set_value_b(::google::protobuf::uint64 value) {
  
  value_b_ = value;
  // @@protoc_insertion_point(field_set:pas.TwoIntegers.value_b)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace pas

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::pas::LogLevel> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::pas::LogLevel>() {
  return ::pas::LogLevel_descriptor();
}
template <> struct is_proto_enum< ::pas::Type> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::pas::Type>() {
  return ::pas::Type_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_commands_2eproto__INCLUDED
