// Code generated by protoc-gen-go.
// source: commands.proto
// DO NOT EDIT!

/*
Package pas is a generated protocol buffer package.

It is generated from these files:
	commands.proto

It has these top-level messages:
	Row
	DacInfo
	SelectResult
	GenericPB
	PlayTrackCommand
	PauseDeviceCommand
	ResumeDeviceCommand
	ClearDeviceCommand
	StopDeviceCommand
	WhoDeviceCommand
	WhatDeviceCommand
	TrackCountQuery
	ArtistCountQuery
	FolderCountQuery
	SelectQuery
	WhenDeviceCommand
	OneInteger
	OneString
	OneFloat
*/
package pas

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Type int32

const (
	Type_GENERIC           Type = 0
	Type_PLAY_TRACK_DEVICE Type = 1
	Type_PAUSE_DEVICE      Type = 2
	Type_RESUME_DEVICE     Type = 3
	Type_STOP_DEVICE       Type = 4
	Type_WHO_DEVICE        Type = 5
	Type_WHAT_DEVICE       Type = 6
	Type_TRACK_COUNT       Type = 7
	Type_ARTIST_COUNT      Type = 8
	Type_FOLDER_COUNT      Type = 9
	Type_SELECT_QUERY      Type = 10
	Type_WHEN_DEVICE       Type = 12
	Type_CLEAR_DEVICE      Type = 13
	Type_SELECT_RESULT     Type = 14
	Type_ROW               Type = 15
	Type_ONE_INT           Type = 16
	Type_ONE_STRING        Type = 17
	Type_ONE_FLOAT         Type = 18
	Type_DAC_INFO_COMMAND  Type = 19
)

var Type_name = map[int32]string{
	0:  "GENERIC",
	1:  "PLAY_TRACK_DEVICE",
	2:  "PAUSE_DEVICE",
	3:  "RESUME_DEVICE",
	4:  "STOP_DEVICE",
	5:  "WHO_DEVICE",
	6:  "WHAT_DEVICE",
	7:  "TRACK_COUNT",
	8:  "ARTIST_COUNT",
	9:  "FOLDER_COUNT",
	10: "SELECT_QUERY",
	12: "WHEN_DEVICE",
	13: "CLEAR_DEVICE",
	14: "SELECT_RESULT",
	15: "ROW",
	16: "ONE_INT",
	17: "ONE_STRING",
	18: "ONE_FLOAT",
	19: "DAC_INFO_COMMAND",
}
var Type_value = map[string]int32{
	"GENERIC":           0,
	"PLAY_TRACK_DEVICE": 1,
	"PAUSE_DEVICE":      2,
	"RESUME_DEVICE":     3,
	"STOP_DEVICE":       4,
	"WHO_DEVICE":        5,
	"WHAT_DEVICE":       6,
	"TRACK_COUNT":       7,
	"ARTIST_COUNT":      8,
	"FOLDER_COUNT":      9,
	"SELECT_QUERY":      10,
	"WHEN_DEVICE":       12,
	"CLEAR_DEVICE":      13,
	"SELECT_RESULT":     14,
	"ROW":               15,
	"ONE_INT":           16,
	"ONE_STRING":        17,
	"ONE_FLOAT":         18,
	"DAC_INFO_COMMAND":  19,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}
func (Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// This is a return type
type Row struct {
	Type    Type              `protobuf:"varint,1,opt,name=type,enum=pas.Type" json:"type,omitempty"`
	Results map[string]string `protobuf:"bytes,2,rep,name=results" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Row) Reset()                    { *m = Row{} }
func (m *Row) String() string            { return proto.CompactTextString(m) }
func (*Row) ProtoMessage()               {}
func (*Row) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Row) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_GENERIC
}

func (m *Row) GetResults() map[string]string {
	if m != nil {
		return m.Results
	}
	return nil
}

// This is a command type
// It expects a SelectResult in response.
type DacInfo struct {
	Type Type   `protobuf:"varint,1,opt,name=type,enum=pas.Type" json:"type,omitempty"`
	Row  []*Row `protobuf:"bytes,2,rep,name=row" json:"row,omitempty"`
}

func (m *DacInfo) Reset()                    { *m = DacInfo{} }
func (m *DacInfo) String() string            { return proto.CompactTextString(m) }
func (*DacInfo) ProtoMessage()               {}
func (*DacInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DacInfo) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_GENERIC
}

func (m *DacInfo) GetRow() []*Row {
	if m != nil {
		return m.Row
	}
	return nil
}

// This is a return type
type SelectResult struct {
	Type Type   `protobuf:"varint,1,opt,name=type,enum=pas.Type" json:"type,omitempty"`
	Row  []*Row `protobuf:"bytes,2,rep,name=row" json:"row,omitempty"`
}

func (m *SelectResult) Reset()                    { *m = SelectResult{} }
func (m *SelectResult) String() string            { return proto.CompactTextString(m) }
func (*SelectResult) ProtoMessage()               {}
func (*SelectResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SelectResult) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_GENERIC
}

func (m *SelectResult) GetRow() []*Row {
	if m != nil {
		return m.Row
	}
	return nil
}

type GenericPB struct {
	Type Type `protobuf:"varint,1,opt,name=type,enum=pas.Type" json:"type,omitempty"`
}

func (m *GenericPB) Reset()                    { *m = GenericPB{} }
func (m *GenericPB) String() string            { return proto.CompactTextString(m) }
func (*GenericPB) ProtoMessage()               {}
func (*GenericPB) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GenericPB) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_GENERIC
}

// This is a send type.
// No respnse is expected.
type PlayTrackCommand struct {
	Type     Type   `protobuf:"varint,1,opt,name=type,enum=pas.Type" json:"type,omitempty"`
	DeviceId uint64 `protobuf:"varint,2,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
	TrackId  uint64 `protobuf:"varint,3,opt,name=track_id,json=trackId" json:"track_id,omitempty"`
}

func (m *PlayTrackCommand) Reset()                    { *m = PlayTrackCommand{} }
func (m *PlayTrackCommand) String() string            { return proto.CompactTextString(m) }
func (*PlayTrackCommand) ProtoMessage()               {}
func (*PlayTrackCommand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PlayTrackCommand) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_GENERIC
}

func (m *PlayTrackCommand) GetDeviceId() uint64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *PlayTrackCommand) GetTrackId() uint64 {
	if m != nil {
		return m.TrackId
	}
	return 0
}

// This is a send type.
// No respnse is expected.
type PauseDeviceCommand struct {
	Type     Type   `protobuf:"varint,1,opt,name=type,enum=pas.Type" json:"type,omitempty"`
	DeviceId uint64 `protobuf:"varint,2,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
}

func (m *PauseDeviceCommand) Reset()                    { *m = PauseDeviceCommand{} }
func (m *PauseDeviceCommand) String() string            { return proto.CompactTextString(m) }
func (*PauseDeviceCommand) ProtoMessage()               {}
func (*PauseDeviceCommand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PauseDeviceCommand) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_GENERIC
}

func (m *PauseDeviceCommand) GetDeviceId() uint64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

// This is a send type.
// No respnse is expected.
type ResumeDeviceCommand struct {
	Type     Type   `protobuf:"varint,1,opt,name=type,enum=pas.Type" json:"type,omitempty"`
	DeviceId uint64 `protobuf:"varint,2,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
}

func (m *ResumeDeviceCommand) Reset()                    { *m = ResumeDeviceCommand{} }
func (m *ResumeDeviceCommand) String() string            { return proto.CompactTextString(m) }
func (*ResumeDeviceCommand) ProtoMessage()               {}
func (*ResumeDeviceCommand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ResumeDeviceCommand) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_GENERIC
}

func (m *ResumeDeviceCommand) GetDeviceId() uint64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

// This is a send type.
// No respnse is expected.
type ClearDeviceCommand struct {
	Type     Type   `protobuf:"varint,1,opt,name=type,enum=pas.Type" json:"type,omitempty"`
	DeviceId uint64 `protobuf:"varint,2,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
}

func (m *ClearDeviceCommand) Reset()                    { *m = ClearDeviceCommand{} }
func (m *ClearDeviceCommand) String() string            { return proto.CompactTextString(m) }
func (*ClearDeviceCommand) ProtoMessage()               {}
func (*ClearDeviceCommand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ClearDeviceCommand) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_GENERIC
}

func (m *ClearDeviceCommand) GetDeviceId() uint64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

// This is a send type.
// No respnse is expected.
type StopDeviceCommand struct {
	Type     Type   `protobuf:"varint,1,opt,name=type,enum=pas.Type" json:"type,omitempty"`
	DeviceId uint64 `protobuf:"varint,2,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
}

func (m *StopDeviceCommand) Reset()                    { *m = StopDeviceCommand{} }
func (m *StopDeviceCommand) String() string            { return proto.CompactTextString(m) }
func (*StopDeviceCommand) ProtoMessage()               {}
func (*StopDeviceCommand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *StopDeviceCommand) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_GENERIC
}

func (m *StopDeviceCommand) GetDeviceId() uint64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

// This is a send type.
// A OneString is expected back.
type WhoDeviceCommand struct {
	Type     Type   `protobuf:"varint,1,opt,name=type,enum=pas.Type" json:"type,omitempty"`
	DeviceId uint64 `protobuf:"varint,2,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
}

func (m *WhoDeviceCommand) Reset()                    { *m = WhoDeviceCommand{} }
func (m *WhoDeviceCommand) String() string            { return proto.CompactTextString(m) }
func (*WhoDeviceCommand) ProtoMessage()               {}
func (*WhoDeviceCommand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *WhoDeviceCommand) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_GENERIC
}

func (m *WhoDeviceCommand) GetDeviceId() uint64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

// This is a send type.
// A OneString is expected back.
type WhatDeviceCommand struct {
	Type     Type   `protobuf:"varint,1,opt,name=type,enum=pas.Type" json:"type,omitempty"`
	DeviceId uint64 `protobuf:"varint,2,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
}

func (m *WhatDeviceCommand) Reset()                    { *m = WhatDeviceCommand{} }
func (m *WhatDeviceCommand) String() string            { return proto.CompactTextString(m) }
func (*WhatDeviceCommand) ProtoMessage()               {}
func (*WhatDeviceCommand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *WhatDeviceCommand) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_GENERIC
}

func (m *WhatDeviceCommand) GetDeviceId() uint64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

// This is a send type.
// A OneInteger is expected back.
type TrackCountQuery struct {
	Type Type `protobuf:"varint,1,opt,name=type,enum=pas.Type" json:"type,omitempty"`
}

func (m *TrackCountQuery) Reset()                    { *m = TrackCountQuery{} }
func (m *TrackCountQuery) String() string            { return proto.CompactTextString(m) }
func (*TrackCountQuery) ProtoMessage()               {}
func (*TrackCountQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *TrackCountQuery) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_GENERIC
}

// This is a send type.
// A OneInteger is expected back.
type ArtistCountQuery struct {
	Type Type `protobuf:"varint,1,opt,name=type,enum=pas.Type" json:"type,omitempty"`
}

func (m *ArtistCountQuery) Reset()                    { *m = ArtistCountQuery{} }
func (m *ArtistCountQuery) String() string            { return proto.CompactTextString(m) }
func (*ArtistCountQuery) ProtoMessage()               {}
func (*ArtistCountQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ArtistCountQuery) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_GENERIC
}

type FolderCountQuery struct {
	Type Type `protobuf:"varint,1,opt,name=type,enum=pas.Type" json:"type,omitempty"`
}

func (m *FolderCountQuery) Reset()                    { *m = FolderCountQuery{} }
func (m *FolderCountQuery) String() string            { return proto.CompactTextString(m) }
func (*FolderCountQuery) ProtoMessage()               {}
func (*FolderCountQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *FolderCountQuery) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_GENERIC
}

// This is a send type.
// A SelectResult is expected back.
type SelectQuery struct {
	Type    Type   `protobuf:"varint,1,opt,name=type,enum=pas.Type" json:"type,omitempty"`
	Column  string `protobuf:"bytes,2,opt,name=column" json:"column,omitempty"`
	Pattern string `protobuf:"bytes,3,opt,name=pattern" json:"pattern,omitempty"`
}

func (m *SelectQuery) Reset()                    { *m = SelectQuery{} }
func (m *SelectQuery) String() string            { return proto.CompactTextString(m) }
func (*SelectQuery) ProtoMessage()               {}
func (*SelectQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *SelectQuery) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_GENERIC
}

func (m *SelectQuery) GetColumn() string {
	if m != nil {
		return m.Column
	}
	return ""
}

func (m *SelectQuery) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

// This is a send type.
// A OneString is expected back.
type WhenDeviceCommand struct {
	Type     Type   `protobuf:"varint,1,opt,name=type,enum=pas.Type" json:"type,omitempty"`
	DeviceId uint64 `protobuf:"varint,2,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
}

func (m *WhenDeviceCommand) Reset()                    { *m = WhenDeviceCommand{} }
func (m *WhenDeviceCommand) String() string            { return proto.CompactTextString(m) }
func (*WhenDeviceCommand) ProtoMessage()               {}
func (*WhenDeviceCommand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *WhenDeviceCommand) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_GENERIC
}

func (m *WhenDeviceCommand) GetDeviceId() uint64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

// This is a return type.
type OneInteger struct {
	Type  Type   `protobuf:"varint,1,opt,name=type,enum=pas.Type" json:"type,omitempty"`
	Value uint64 `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
}

func (m *OneInteger) Reset()                    { *m = OneInteger{} }
func (m *OneInteger) String() string            { return proto.CompactTextString(m) }
func (*OneInteger) ProtoMessage()               {}
func (*OneInteger) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *OneInteger) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_GENERIC
}

func (m *OneInteger) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

// This is a return type.
type OneString struct {
	Type  Type   `protobuf:"varint,1,opt,name=type,enum=pas.Type" json:"type,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *OneString) Reset()                    { *m = OneString{} }
func (m *OneString) String() string            { return proto.CompactTextString(m) }
func (*OneString) ProtoMessage()               {}
func (*OneString) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *OneString) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_GENERIC
}

func (m *OneString) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// This is a return type.
type OneFloat struct {
	Type  Type    `protobuf:"varint,1,opt,name=type,enum=pas.Type" json:"type,omitempty"`
	Value float32 `protobuf:"fixed32,2,opt,name=value" json:"value,omitempty"`
}

func (m *OneFloat) Reset()                    { *m = OneFloat{} }
func (m *OneFloat) String() string            { return proto.CompactTextString(m) }
func (*OneFloat) ProtoMessage()               {}
func (*OneFloat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *OneFloat) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_GENERIC
}

func (m *OneFloat) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*Row)(nil), "pas.Row")
	proto.RegisterType((*DacInfo)(nil), "pas.DacInfo")
	proto.RegisterType((*SelectResult)(nil), "pas.SelectResult")
	proto.RegisterType((*GenericPB)(nil), "pas.GenericPB")
	proto.RegisterType((*PlayTrackCommand)(nil), "pas.PlayTrackCommand")
	proto.RegisterType((*PauseDeviceCommand)(nil), "pas.PauseDeviceCommand")
	proto.RegisterType((*ResumeDeviceCommand)(nil), "pas.ResumeDeviceCommand")
	proto.RegisterType((*ClearDeviceCommand)(nil), "pas.ClearDeviceCommand")
	proto.RegisterType((*StopDeviceCommand)(nil), "pas.StopDeviceCommand")
	proto.RegisterType((*WhoDeviceCommand)(nil), "pas.WhoDeviceCommand")
	proto.RegisterType((*WhatDeviceCommand)(nil), "pas.WhatDeviceCommand")
	proto.RegisterType((*TrackCountQuery)(nil), "pas.TrackCountQuery")
	proto.RegisterType((*ArtistCountQuery)(nil), "pas.ArtistCountQuery")
	proto.RegisterType((*FolderCountQuery)(nil), "pas.FolderCountQuery")
	proto.RegisterType((*SelectQuery)(nil), "pas.SelectQuery")
	proto.RegisterType((*WhenDeviceCommand)(nil), "pas.WhenDeviceCommand")
	proto.RegisterType((*OneInteger)(nil), "pas.OneInteger")
	proto.RegisterType((*OneString)(nil), "pas.OneString")
	proto.RegisterType((*OneFloat)(nil), "pas.OneFloat")
	proto.RegisterEnum("pas.Type", Type_name, Type_value)
}

func init() { proto.RegisterFile("commands.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 642 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x95, 0xcf, 0x4e, 0xdb, 0x4a,
	0x14, 0xc6, 0x6f, 0xe2, 0x80, 0xe3, 0x43, 0x08, 0x93, 0xe1, 0x72, 0xc5, 0xa5, 0xaa, 0x84, 0xbc,
	0x42, 0x2c, 0xd2, 0x96, 0x6e, 0x2a, 0x36, 0xad, 0x6b, 0x4f, 0xc0, 0x6a, 0xb0, 0xcd, 0xd8, 0x69,
	0xc4, 0xa6, 0x91, 0xeb, 0x4c, 0x21, 0xc2, 0xb1, 0x23, 0x67, 0x02, 0xca, 0x63, 0xf4, 0xb1, 0xfa,
	0x56, 0x9d, 0xf1, 0x9f, 0xaa, 0x5d, 0x05, 0x54, 0xef, 0x7c, 0xbe, 0xf9, 0xe6, 0x37, 0x9f, 0x8e,
	0xe7, 0x0f, 0x74, 0xa3, 0x74, 0x3e, 0x0f, 0x93, 0xe9, 0xb2, 0xbf, 0xc8, 0x52, 0x9e, 0x62, 0x65,
	0x11, 0x2e, 0xf5, 0xef, 0x0d, 0x50, 0x68, 0xfa, 0x88, 0x5f, 0x42, 0x8b, 0xaf, 0x17, 0xec, 0xb0,
	0x71, 0xdc, 0x38, 0xe9, 0x9e, 0x69, 0x7d, 0x31, 0xd6, 0x0f, 0x84, 0x40, 0x73, 0x19, 0xbf, 0x02,
	0x35, 0x63, 0xcb, 0x55, 0xcc, 0x97, 0x87, 0xcd, 0x63, 0xe5, 0x64, 0xe7, 0xec, 0x20, 0x77, 0x88,
	0x99, 0x7d, 0x5a, 0xe8, 0x24, 0xe1, 0xd9, 0x9a, 0x56, 0xae, 0xa3, 0x73, 0xe8, 0xfc, 0x3e, 0x80,
	0x11, 0x28, 0xf7, 0x6c, 0x9d, 0xe3, 0x35, 0x2a, 0x3f, 0xf1, 0xbf, 0xb0, 0xf5, 0x10, 0xc6, 0x2b,
	0x26, 0x80, 0x52, 0x2b, 0x8a, 0xf3, 0xe6, 0xbb, 0x86, 0x6e, 0x81, 0x6a, 0x85, 0x91, 0x9d, 0x7c,
	0x4b, 0x37, 0xc5, 0x3a, 0x02, 0x25, 0x4b, 0x1f, 0xcb, 0x48, 0xed, 0x2a, 0x12, 0x95, 0xa2, 0x6e,
	0x43, 0xc7, 0x67, 0x31, 0x8b, 0x78, 0x91, 0xe3, 0x6f, 0x50, 0xa7, 0xa0, 0x5d, 0xb0, 0x84, 0x65,
	0xb3, 0xc8, 0xfb, 0xb8, 0x81, 0xa3, 0xcf, 0x00, 0x79, 0x71, 0xb8, 0x0e, 0xb2, 0x30, 0xba, 0x37,
	0x8b, 0x86, 0x6f, 0x5a, 0xfa, 0x05, 0x68, 0x53, 0xf6, 0x30, 0x8b, 0xd8, 0x64, 0x36, 0xcd, 0xbb,
	0xd1, 0xa2, 0xed, 0x42, 0xb0, 0xa7, 0xf8, 0x7f, 0x68, 0x73, 0xc9, 0x92, 0x63, 0x4a, 0x3e, 0xa6,
	0xe6, 0xb5, 0x3d, 0xd5, 0x3d, 0xc0, 0x5e, 0xb8, 0x5a, 0x32, 0x2b, 0xf7, 0xd6, 0xb0, 0x98, 0x7e,
	0x0d, 0xfb, 0xb2, 0x5b, 0xf3, 0x1a, 0x91, 0x22, 0xa4, 0x19, 0xb3, 0x30, 0xab, 0x8f, 0xe8, 0x42,
	0xcf, 0xe7, 0xe9, 0xa2, 0x3e, 0xa0, 0x03, 0x68, 0x7c, 0x97, 0xd6, 0x1a, 0x70, 0x7c, 0x17, 0xf2,
	0xfa, 0x80, 0xaf, 0x61, 0xaf, 0xdc, 0x4f, 0xab, 0x84, 0x5f, 0xaf, 0x98, 0x38, 0x4f, 0x1b, 0x76,
	0xe1, 0x1b, 0x40, 0x46, 0xc6, 0x67, 0x4b, 0xfe, 0xac, 0x29, 0x83, 0x34, 0x9e, 0xb2, 0xec, 0xe9,
	0x53, 0xbe, 0xc0, 0x4e, 0x71, 0xc4, 0x9e, 0xe2, 0xc6, 0xff, 0xc1, 0x76, 0x94, 0xc6, 0xab, 0x79,
	0x52, 0x9e, 0xf8, 0xb2, 0xc2, 0x87, 0xa0, 0x2e, 0x42, 0xce, 0x59, 0x96, 0xe4, 0x1b, 0x5c, 0xa3,
	0x55, 0x59, 0x34, 0x92, 0x25, 0xf5, 0x35, 0xd2, 0x00, 0x70, 0x13, 0x66, 0x27, 0x9c, 0xdd, 0xb2,
	0x6c, 0x13, 0xe9, 0x8f, 0x0b, 0xaa, 0x55, 0x5e, 0x50, 0xfa, 0x07, 0xd0, 0x04, 0xc2, 0xe7, 0xd9,
	0x2c, 0xb9, 0x7d, 0x16, 0xa1, 0xba, 0xe2, 0xf4, 0xf7, 0xd0, 0x16, 0x84, 0x41, 0x9c, 0x86, 0xfc,
	0x59, 0x80, 0x66, 0x09, 0x38, 0xfd, 0xd1, 0x84, 0x96, 0x34, 0xe1, 0x1d, 0x50, 0x2f, 0x88, 0x43,
	0xa8, 0x6d, 0xa2, 0x7f, 0xf0, 0x01, 0xf4, 0xbc, 0xa1, 0x71, 0x33, 0x09, 0xa8, 0x61, 0x7e, 0x9a,
	0x58, 0xe4, 0xb3, 0x6d, 0x12, 0xd4, 0x10, 0x17, 0x6f, 0xc7, 0x33, 0x46, 0x3e, 0xa9, 0x94, 0x26,
	0xee, 0xc1, 0x2e, 0x25, 0xfe, 0xe8, 0xea, 0x97, 0xa4, 0xe0, 0x3d, 0xf1, 0x23, 0x03, 0xd7, 0xab,
	0x84, 0x16, 0xee, 0x02, 0x8c, 0x2f, 0xdd, 0xaa, 0xde, 0x92, 0x86, 0xf1, 0xa5, 0x11, 0x54, 0xc2,
	0xb6, 0x14, 0x8a, 0x85, 0x4c, 0x77, 0xe4, 0x04, 0x48, 0x95, 0xeb, 0x18, 0x34, 0xb0, 0xfd, 0xa0,
	0x54, 0xda, 0x52, 0x19, 0xb8, 0x43, 0x8b, 0xd0, 0x52, 0xd1, 0xa4, 0xe2, 0x93, 0x21, 0x31, 0x83,
	0xc9, 0xf5, 0x88, 0xd0, 0x1b, 0x04, 0x05, 0x97, 0x38, 0x15, 0xb7, 0x23, 0x2d, 0xe6, 0x90, 0x18,
	0xb4, 0x52, 0x76, 0x65, 0xdc, 0x72, 0x92, 0x4c, 0x3d, 0x0c, 0x50, 0x17, 0xab, 0xe2, 0xcd, 0x72,
	0xc7, 0x68, 0x4f, 0x36, 0xc0, 0x75, 0xc8, 0xc4, 0x16, 0x74, 0x24, 0x33, 0xcb, 0xc2, 0x0f, 0xa8,
	0xed, 0x5c, 0xa0, 0x1e, 0xde, 0x15, 0x7f, 0x4a, 0xd4, 0x83, 0xa1, 0x6b, 0x04, 0x08, 0x8b, 0x5e,
	0x22, 0xcb, 0x30, 0x85, 0x77, 0xe0, 0x8a, 0x40, 0x57, 0x57, 0x86, 0x63, 0xa1, 0xfd, 0xaf, 0xdb,
	0xf9, 0x5b, 0xf8, 0xf6, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x55, 0xcb, 0xda, 0x1d, 0x07,
	0x00, 0x00,
}
